// <auto-generated />
namespace MeetUp.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TrackingRedesign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrackingRedesign));
        
        string IMigrationMetadata.Id
        {
            get { return "201809081507360_TrackingRedesign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
