// <auto-generated />
namespace MeetUp.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ResolvewidermodelrequiredfororderHTML : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResolvewidermodelrequiredfororderHTML));
        
        string IMigrationMetadata.Id
        {
            get { return "201809172303048_Resolve wider model required for order HTML"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
